run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gosec
  disable:
    - revive
    - unconvert
    - unparam
    - gocritic
    - gocyclo
    - godot
    - whitespace
    - wsl
    - nlreturn

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true


  gosec:
    severity: "low"
    confidence: "low"

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  gocyclo:
    min-complexity: 15

  whitespace:
    multi-if: false
    multi-func: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - gocyclo
    - path: cmd/
      linters:
        - gocyclo
  max-issues-per-linter: 0
  max-same-issues: 0