version: '3'

vars:
  CURRENT_VERSION:
    sh: grep '^version = ' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  version:
    desc: Show current version
    cmds:
      - echo "Current version {{.CURRENT_VERSION}}"

  version-set:
    desc: Set version (usage {{.TASK}} VERSION=x.x.x)
    preconditions:
      - sh: '[ -n "{{.VERSION}}" ]'
        msg: "VERSION is required"
    cmds:
      - echo "Updating version from {{.CURRENT_VERSION}} to {{.VERSION}}"
      - sed -i '' 's/^version = ".*"/version = "{{.VERSION}}"/' Cargo.toml
      - sed -i '' 's/^version = ".*"/version = "{{.VERSION}}"/' pyproject.toml
      - echo "Updated files"
      - grep '^version = ' Cargo.toml
      - grep '^version = ' pyproject.toml

  version-bump-patch:
    desc: Bump patch version (0.0.x)
    vars:
      NEW_VERSION:
        sh: echo {{.CURRENT_VERSION}} | awk -F. '{print $1"."$2"."$3+1}'
    cmds:
      - task: version-set
        vars:
          VERSION: '{{.NEW_VERSION}}'

  version-bump-minor:
    desc: Bump minor version (0.x.0)
    vars:
      NEW_VERSION:
        sh: echo {{.CURRENT_VERSION}} | awk -F. '{print $1"."$2+1".0"}'
    cmds:
      - task: version-set
        vars:
          VERSION: '{{.NEW_VERSION}}'

  version-bump-major:
    desc: Bump major version (x.0.0)
    vars:
      NEW_VERSION:
        sh: echo {{.CURRENT_VERSION}} | awk -F. '{print $1+1".0.0"}'
    cmds:
      - task: version-set
        vars:
          VERSION: '{{.NEW_VERSION}}'

  release:
    desc: Create release tag (usage {{.TASK}} VERSION=x.x.x)
    preconditions:
      - sh: '[ -n "{{.VERSION}}" ]'
        msg: "VERSION is required"
    cmds:
      - task: version-set
        vars:
          VERSION: '{{.VERSION}}'
      - git add Cargo.toml pyproject.toml
      - cmd: git commit -m "chore{{":"}} bump version to {{.VERSION}}"
      - cmd: git tag v{{.VERSION}}
      - cmd: echo "Created tag v{{.VERSION}}"
      - cmd: echo "Run 'git push && git push origin v{{.VERSION}}' to trigger release"

  build:
    desc: Build the project
    cmds:
      - cargo build --release

  test:
    desc: Run all tests
    cmds:
      - cargo test

  lint:
    desc: Run linters
    cmds:
      - cargo fmt --check
      - cargo clippy -- -D warnings

  dev:
    desc: Build Python package for development
    cmds:
      - maturin develop
