name: LLM Code Review

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  llm-code-review:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.go
            **/*.md
            **/*.yml
            **/*.yaml
            **/*.json

      - name: AI Code Review with GitHub Models
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: freeedcom/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_MODEL: "gpt-4"
          exclude: "**/*.sum,**/*.mod,**/vendor/**"
