name: Auto Request Copilot Review

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  request-copilot-review:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    
    steps:
      - name: Request GitHub Copilot Review
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // GitHub CopilotにPRレビューをリクエスト
            const { owner, repo, number } = context.issue;
            
            try {
              // Copilotをレビュアーとして追加
              await github.rest.pulls.requestReviewers({
                owner: owner,
                repo: repo,
                pull_number: number,
                reviewers: ['copilot[bot]']
              });
              
              console.log('GitHub Copilotにレビューをリクエストしました');
            } catch (error) {
              console.log('Copilotレビューのリクエストに失敗:', error.message);
              // エラーが発生してもワークフローは続行
            }